program fjf141;

{$W-}
{$AVeryLongCompilerDirectiveWillOverflowSomeStaticBuffersOfThePreprocessorAndLexerAVeryLongCompilerDirectiveWillOverflowSomeStaticBuffersOfThePreprocessorAndLexerAVeryLongCompilerDirectiveWillOverflowSomeStaticBuffersOfThePreprocessorAndLexerAVeryLongCompilerDirectiveWillOverflowSomeStaticBuffersOfThePreprocessorAndLexerAVeryLongCompilerDirectiveWillOverflowSomeStaticBuffersOfThePreprocessorAndLexerAVeryLongCompilerDirectiveWillOverflowSomeStaticBuffersOfThePreprocessorAndLexerAVeryLongCompilerDirectiveWillOverflowSomeStaticBuffersOfThePreprocessorAndLexerAVeryLongCompilerDirectiveWillOverflowSomeStaticBuffersOfThePreprocessorAndLexerAVeryLongCompilerDirectiveWillOverflowSomeStaticBuffersOfThePreprocessorAndLexer}
{$W+}

begin
  WriteLn ('OK')
end.
