program fjf89;

type
  AnObjectTypeWithAVeryLongNameWillOverflowAStaticBufferInTheCompilerAnObjectTypeWithAVeryLongNameWillOverflowAStaticBufferInTheCompilerAnObjectTypeWithAVeryLongNameWillOverflowAStaticBufferInTheCompilerAnObjectTypeWithAVeryLongNameWillOverflowAStaticBufferInTheCompilerAnObjectTypeWithAVeryLongNameWillOverflowAStaticBufferInTheCompilerAnObjectTypeWithAVeryLongNameWillOverflowAStaticBufferInTheCompilerAnObjectTypeWithAVeryLongNameWillOverflowAStaticBufferInTheCompilerAnObjectTypeWithAVeryLongNameWillOverflowAStaticBufferInTheCompilerAnObjectTypeWithAVeryLongNameWillOverflowAStaticBufferInTheCompiler = object
    constructor Foo;
  end;

constructor AnObjectTypeWithAVeryLongNameWillOverflowAStaticBufferInTheCompilerAnObjectTypeWithAVeryLongNameWillOverflowAStaticBufferInTheCompilerAnObjectTypeWithAVeryLongNameWillOverflowAStaticBufferInTheCompilerAnObjectTypeWithAVeryLongNameWillOverflowAStaticBufferInTheCompilerAnObjectTypeWithAVeryLongNameWillOverflowAStaticBufferInTheCompilerAnObjectTypeWithAVeryLongNameWillOverflowAStaticBufferInTheCompilerAnObjectTypeWithAVeryLongNameWillOverflowAStaticBufferInTheCompilerAnObjectTypeWithAVeryLongNameWillOverflowAStaticBufferInTheCompilerAnObjectTypeWithAVeryLongNameWillOverflowAStaticBufferInTheCompiler.Foo;
begin
  WriteLn ('OK')
end;

var
  o : AnObjectTypeWithAVeryLongNameWillOverflowAStaticBufferInTheCompilerAnObjectTypeWithAVeryLongNameWillOverflowAStaticBufferInTheCompilerAnObjectTypeWithAVeryLongNameWillOverflowAStaticBufferInTheCompilerAnObjectTypeWithAVeryLongNameWillOverflowAStaticBufferInTheCompilerAnObjectTypeWithAVeryLongNameWillOverflowAStaticBufferInTheCompilerAnObjectTypeWithAVeryLongNameWillOverflowAStaticBufferInTheCompilerAnObjectTypeWithAVeryLongNameWillOverflowAStaticBufferInTheCompilerAnObjectTypeWithAVeryLongNameWillOverflowAStaticBufferInTheCompilerAnObjectTypeWithAVeryLongNameWillOverflowAStaticBufferInTheCompiler;

begin
  o.Foo
end.
