#ifdef ARMEB
  do_def ("ARMEB");
#endif
#ifdef ARMEL
  do_def ("ARMEL");
#endif
#ifdef CPU
  do_def ("CPU");
#endif
#ifdef CPU_VARIANT
  do_def ("CPU_VARIANT");
#endif
#ifdef PWB
  do_def ("PWB");
#endif
#ifdef SVR4
  do_def ("SVR4");
#endif
#ifdef VSTA
  do_def ("VSTA");
#endif
#ifdef _ADDR64
  do_def ("_ADDR64");
#endif
#ifdef _AIX
  do_def ("_AIX");
#endif
#ifdef _AIX32
  do_def ("_AIX32");
#endif
#ifdef _AIX41
  do_def ("_AIX41");
#endif
#ifdef _AIX43
  do_def ("_AIX43");
#endif
#ifdef _AIX51
  do_def ("_AIX51");
#endif
#ifdef _AIX52
  do_def ("_AIX52");
#endif
#ifdef _ARCH_COM
  do_def ("_ARCH_COM");
#endif
#ifdef _ARCH_PPC
  do_def ("_ARCH_PPC");
#endif
#ifdef _ARCH_PPC64
  do_def ("_ARCH_PPC64");
#endif
#ifdef _ARCH_PWR
  do_def ("_ARCH_PWR");
#endif
#ifdef _ARCH_PWR2
  do_def ("_ARCH_PWR2");
#endif
#ifdef _BIGMODEL
  do_def ("_BIGMODEL");
#endif
#ifdef _BIG_ENDIAN
  do_def ("_BIG_ENDIAN");
#endif
#ifdef _C30
  do_def ("_C30");
#endif
#ifdef _C31
  do_def ("_C31");
#endif
#ifdef _C32
  do_def ("_C32");
#endif
#ifdef _C33
  do_def ("_C33");
#endif
#ifdef _C3x
  do_def ("_C3x");
#endif
#ifdef _C40
  do_def ("_C40");
#endif
#ifdef _C44
  do_def ("_C44");
#endif
#ifdef _C4x
  do_def ("_C4x");
#endif
#ifdef _CALL_AIX
  do_def ("_CALL_AIX");
#endif
#ifdef _CALL_AIXDESC
  do_def ("_CALL_AIXDESC");
#endif
#ifdef _CALL_DARWIN
  do_def ("_CALL_DARWIN");
#endif
#ifdef _CALL_SYSV
  do_def ("_CALL_SYSV");
#endif
#ifdef _CRAY
  do_def ("_CRAY");
#endif
#ifdef _CRAYIEEE
  do_def ("_CRAYIEEE");
#endif
#ifdef _CRAYMPP
  do_def ("_CRAYMPP");
#endif
#ifdef _CRAYT3E
  do_def ("_CRAYT3E");
#endif
#ifdef _DOUBLE_IS_32BITS
  do_def ("_DOUBLE_IS_32BITS");
#endif
#ifdef _GNU_SOURCE
  do_def ("_GNU_SOURCE");
#endif
#ifdef _HPUX_SOURCE
  do_def ("_HPUX_SOURCE");
#endif
#ifdef _IBMR2
  do_def ("_IBMR2");
#endif
#ifdef _IEEE_FP
  do_def ("_IEEE_FP");
#endif
#ifdef _IEEE_FP_INEXACT
  do_def ("_IEEE_FP_INEXACT");
#endif
#ifdef _ILP32
  do_def ("_ILP32");
#endif
#ifdef _INCLUDE_LONGLONG
  do_def ("_INCLUDE_LONGLONG");
#endif
#ifdef _INLINE
  do_def ("_INLINE");
#endif
#ifdef _LANGUAGE_ASSEMBLY
  do_def ("_LANGUAGE_ASSEMBLY");
#endif
#ifdef _LANGUAGE_C
  do_def ("_LANGUAGE_C");
#endif
#ifdef _LANGUAGE_C_PLUS_PLUS
  do_def ("_LANGUAGE_C_PLUS_PLUS");
#endif
#ifdef _LANGUAGE_OBJECTIVE_C
  do_def ("_LANGUAGE_OBJECTIVE_C");
#endif
#ifdef _LD64
  do_def ("_LD64");
#endif
#ifdef _LITTLE_ENDIAN
  do_def ("_LITTLE_ENDIAN");
#endif
#ifdef _LONGLONG
  do_def ("_LONGLONG");
#endif
#ifdef _LONG_LONG
  do_def ("_LONG_LONG");
#endif
#ifdef _MIPSEB
  do_def ("_MIPSEB");
#endif
#ifdef _MIPSEL
  do_def ("_MIPSEL");
#endif
#ifdef _MIPS_ISA
  do_def ("_MIPS_ISA");
#endif
#ifdef _MIPS_SIM
  do_def ("_MIPS_SIM");
#endif
#ifdef _MODERN_C
  do_def ("_MODERN_C");
#endif
#ifdef _M_I386
  do_def ("_M_I386");
#endif
#ifdef _M_UNIX
  do_def ("_M_UNIX");
#endif
#ifdef _M_XENIX
  do_def ("_M_XENIX");
#endif
#ifdef _PA_RISC1_0
  do_def ("_PA_RISC1_0");
#endif
#ifdef _PA_RISC1_1
  do_def ("_PA_RISC1_1");
#endif
#ifdef _PA_RISC2_0
  do_def ("_PA_RISC2_0");
#endif
#ifdef _POWER
  do_def ("_POWER");
#endif
#ifdef _PWB
  do_def ("_PWB");
#endif
#ifdef _R3000
  do_def ("_R3000");
#endif
#ifdef _R4000
  do_def ("_R4000");
#endif
#ifdef _REGPARM
  do_def ("_REGPARM");
#endif
#ifdef _RELOCATABLE
  do_def ("_RELOCATABLE");
#endif
#ifdef _SCO_DS
  do_def ("_SCO_DS");
#endif
#ifdef _SCO_DS_LL
  do_def ("_SCO_DS_LL");
#endif
#ifdef _SCO_ELF
  do_def ("_SCO_ELF");
#endif
#ifdef _SEQUENT_
  do_def ("_SEQUENT_");
#endif
#ifdef _SGI_SOURCE
  do_def ("_SGI_SOURCE");
#endif
#ifdef _SIO
  do_def ("_SIO");
#endif
#ifdef _SOFT_FLOAT
  do_def ("_SOFT_FLOAT");
#endif
#ifdef _STD_INCLUDE_DIR
  do_def ("_STD_INCLUDE_DIR");
#endif
#ifdef _SVR4_SOURCE
  do_def ("_SVR4_SOURCE");
#endif
#ifdef _SYSTYPE_BSD
  do_def ("_SYSTYPE_BSD");
#endif
#ifdef _TMS320C30
  do_def ("_TMS320C30");
#endif
#ifdef _TMS320C31
  do_def ("_TMS320C31");
#endif
#ifdef _TMS320C32
  do_def ("_TMS320C32");
#endif
#ifdef _TMS320C33
  do_def ("_TMS320C33");
#endif
#ifdef _TMS320C3x
  do_def ("_TMS320C3x");
#endif
#ifdef _TMS320C40
  do_def ("_TMS320C40");
#endif
#ifdef _TMS320C44
  do_def ("_TMS320C44");
#endif
#ifdef _TMS320C4x
  do_def ("_TMS320C4x");
#endif
#ifdef _UINT128_T
  do_def ("_UINT128_T");
#endif
#ifdef _UWIN
  do_def ("_UWIN");
#endif
#ifdef _WIN32
  do_def ("_WIN32");
#endif
#ifdef _WSIO
  do_def ("_WSIO");
#endif
#ifdef _X86_
  do_def ("_X86_");
#endif
#ifdef __3dNOW_A__
  do_def ("__3dNOW_A__");
#endif
#ifdef __3dNOW__
  do_def ("__3dNOW__");
#endif
#ifdef __ABICALLS__
  do_def ("__ABICALLS__");
#endif
#ifdef __ALPHA
  do_def ("__ALPHA");
#endif
#ifdef __ALTIVEC__
  do_def ("__ALTIVEC__");
#endif
#ifdef __ANSI_COMPAT
  do_def ("__ANSI_COMPAT");
#endif
#ifdef __AOUT__
  do_def ("__AOUT__");
#endif
#ifdef __APCS_26__
  do_def ("__APCS_26__");
#endif
#ifdef __APCS_32__
  do_def ("__APCS_32__");
#endif
#ifdef __APPLE__
  do_def ("__APPLE__");
#endif
#ifdef __APX386__
  do_def ("__APX386__");
#endif
#ifdef __ARMEB__
  do_def ("__ARMEB__");
#endif
#ifdef __ARMEL__
  do_def ("__ARMEL__");
#endif
#ifdef __ARMWEL__
  do_def ("__ARMWEL__");
#endif
#ifdef __AVR_ASM_ONLY__
  do_def ("__AVR_ASM_ONLY__");
#endif
#ifdef __AVR_ENHANCED__
  do_def ("__AVR_ENHANCED__");
#endif
#ifdef __AVR_MEGA__
  do_def ("__AVR_MEGA__");
#endif
#ifdef __AVR__
  do_def ("__AVR__");
#endif
#ifdef __BEOS__
  do_def ("__BEOS__");
#endif
#ifdef __BIG_ENDIAN__
  do_def ("__BIG_ENDIAN__");
#endif
#ifdef __BIT_MSF__
  do_def ("__BIT_MSF__");
#endif
#ifdef __BYTE_MSF__
  do_def ("__BYTE_MSF__");
#endif
#ifdef __CLASSIC_C__
  do_def ("__CLASSIC_C__");
#endif
#ifdef __CRIS__
  do_def ("__CRIS__");
#endif
#ifdef __CRTDLL__
  do_def ("__CRTDLL__");
#endif
#ifdef __D30V__
  do_def ("__D30V__");
#endif
#ifdef __DSO__
  do_def ("__DSO__");
#endif
#ifdef __DSP1600__
  do_def ("__DSP1600__");
#endif
#ifdef __DSP1610__
  do_def ("__DSP1610__");
#endif
#ifdef __ELF__
  do_def ("__ELF__");
#endif
#ifdef __EXTENSIONS__
  do_def ("__EXTENSIONS__");
#endif
#ifdef __FreeBSD__
  do_def ("__FreeBSD__");
#endif
#ifdef __GCC__
  do_def ("__GCC__");
#endif
#ifdef __GFLOAT
  do_def ("__GFLOAT");
#endif
#ifdef __GFLOAT__
  do_def ("__GFLOAT__");
#endif
#ifdef __GNU_CRIS__
  do_def ("__GNU_CRIS__");
#endif
#ifdef __GNU__
  do_def ("__GNU__");
#endif
#ifdef __GO32__
  do_def ("__GO32__");
#endif
#ifdef __GP_SUPPORT__
  do_def ("__GP_SUPPORT__");
#endif
#ifdef __G_FLOAT
  do_def ("__G_FLOAT");
#endif
#ifdef __H8300H__
  do_def ("__H8300H__");
#endif
#ifdef __H8300S__
  do_def ("__H8300S__");
#endif
#ifdef __H8300__
  do_def ("__H8300__");
#endif
#ifdef __HAVE_68881__
  do_def ("__HAVE_68881__");
#endif
#ifdef __HITACHI__
  do_def ("__HITACHI__");
#endif
#ifdef __HP700__
  do_def ("__HP700__");
#endif
#ifdef __I386__
  do_def ("__I386__");
#endif
#ifdef __I80960__
  do_def ("__I80960__");
#endif
#ifdef __I960__
  do_def ("__I960__");
#endif
#ifdef __IA64__
  do_def ("__IA64__");
#endif
#ifdef __IBITS32__
  do_def ("__IBITS32__");
#endif
#ifdef __ID_SHARED_LIBRARY__
  do_def ("__ID_SHARED_LIBRARY__");
#endif
#ifdef __IEEE_FLOAT
  do_def ("__IEEE_FLOAT");
#endif
#ifdef __INTEL__
  do_def ("__INTEL__");
#endif
#ifdef __INTERIX
  do_def ("__INTERIX");
#endif
#ifdef __IP2K__
  do_def ("__IP2K__");
#endif
#ifdef __KPRINTF_ATTRIBUTE__
  do_def ("__KPRINTF_ATTRIBUTE__");
#endif
#ifdef __LANGUAGE_ASSEMBLY__
  do_def ("__LANGUAGE_ASSEMBLY__");
#endif
#ifdef __LANGUAGE_C_PLUS_PLUS
  do_def ("__LANGUAGE_C_PLUS_PLUS");
#endif
#ifdef __LANGUAGE_C_PLUS_PLUS__
  do_def ("__LANGUAGE_C_PLUS_PLUS__");
#endif
#ifdef __LANGUAGE_C__
  do_def ("__LANGUAGE_C__");
#endif
#ifdef __LANGUAGE_OBJECTIVE_C
  do_def ("__LANGUAGE_OBJECTIVE_C");
#endif
#ifdef __LANGUAGE_OBJECTIVE_C__
  do_def ("__LANGUAGE_OBJECTIVE_C__");
#endif
#ifdef __LE370__
  do_def ("__LE370__");
#endif
#ifdef __LITTLE_ENDIAN__
  do_def ("__LITTLE_ENDIAN__");
#endif
#ifdef __LONG64
  do_def ("__LONG64");
#endif
#ifdef __LONG_DOUBLE_128__
  do_def ("__LONG_DOUBLE_128__");
#endif
#ifdef __LP64__
  do_def ("__LP64__");
#endif
#ifdef __LYNX__
  do_def ("__LYNX__");
#endif
#ifdef __Lynx__
  do_def ("__Lynx__");
#endif
#ifdef __M210__
  do_def ("__M210__");
#endif
#ifdef __M32R__
  do_def ("__M32R__");
#endif
#ifdef __M340__
  do_def ("__M340__");
#endif
#ifdef __MACH__
  do_def ("__MACH__");
#endif
#ifdef __MCOREBE__
  do_def ("__MCOREBE__");
#endif
#ifdef __MCORELE__
  do_def ("__MCORELE__");
#endif
#ifdef __MCORE__
  do_def ("__MCORE__");
#endif
#ifdef __MINGW32__
  do_def ("__MINGW32__");
#endif
#ifdef __MIPSEB__
  do_def ("__MIPSEB__");
#endif
#ifdef __MIPSEL__
  do_def ("__MIPSEL__");
#endif
#ifdef __MMIX_ABI_GNU__
  do_def ("__MMIX_ABI_GNU__");
#endif
#ifdef __MMIX_ABI_MMIXWARE__
  do_def ("__MMIX_ABI_MMIXWARE__");
#endif
#ifdef __MMIX__
  do_def ("__MMIX__");
#endif
#ifdef __MMX__
  do_def ("__MMX__");
#endif
#ifdef __MN10300__
  do_def ("__MN10300__");
#endif
#ifdef __MSDOS__
  do_def ("__MSDOS__");
#endif
#ifdef __MSVCRT__
  do_def ("__MSVCRT__");
#endif
#ifdef __MVS__
  do_def ("__MVS__");
#endif
#ifdef __NATURAL_ALIGNMENT__
  do_def ("__NATURAL_ALIGNMENT__");
#endif
#ifdef __NORMAL_MODE__
  do_def ("__NORMAL_MODE__");
#endif
#ifdef __NO_INTERRUPTS__
  do_def ("__NO_INTERRUPTS__");
#endif
#ifdef __NO_LEADING_UNDERSCORES__
  do_def ("__NO_LEADING_UNDERSCORES__");
#endif
#ifdef __NO_UNDERSCORES__
  do_def ("__NO_UNDERSCORES__");
#endif
#ifdef __NetBSD__
  do_def ("__NetBSD__");
#endif
#ifdef __OPENNT
  do_def ("__OPENNT");
#endif
#ifdef __OpenBSD__
  do_def ("__OpenBSD__");
#endif
#ifdef __PARISC__
  do_def ("__PARISC__");
#endif
#ifdef __PIC__
  do_def ("__PIC__");
#endif
#ifdef __PNI__
  do_def ("__PNI__");
#endif
#ifdef __POWERPC__
  do_def ("__POWERPC__");
#endif
#ifdef __PPC405__
  do_def ("__PPC405__");
#endif
#ifdef __PPC64__
  do_def ("__PPC64__");
#endif
#ifdef __PPC__
  do_def ("__PPC__");
#endif
#ifdef __PRAGMA_EXTERN_PREFIX
  do_def ("__PRAGMA_EXTERN_PREFIX");
#endif
#ifdef __PRAGMA_REDEFINE_EXTNAME
  do_def ("__PRAGMA_REDEFINE_EXTNAME");
#endif
#ifdef __PWB__
  do_def ("__PWB__");
#endif
#ifdef __R3000__
  do_def ("__R3000__");
#endif
#ifdef __R4000__
  do_def ("__R4000__");
#endif
#ifdef __REVARGV__
  do_def ("__REVARGV__");
#endif
#ifdef __RTD__
  do_def ("__RTD__");
#endif
#ifdef __SH2E__
  do_def ("__SH2E__");
#endif
#ifdef __SH3E__
  do_def ("__SH3E__");
#endif
#ifdef __SH3__
  do_def ("__SH3__");
#endif
#ifdef __SH4_NOFPU__
  do_def ("__SH4_NOFPU__");
#endif
#ifdef __SH4_SINGLE_ONLY__
  do_def ("__SH4_SINGLE_ONLY__");
#endif
#ifdef __SH4_SINGLE__
  do_def ("__SH4_SINGLE__");
#endif
#ifdef __SH4__
  do_def ("__SH4__");
#endif
#ifdef __SH5__
  do_def ("__SH5__");
#endif
#ifdef __SHMEDIA__
  do_def ("__SHMEDIA__");
#endif
#ifdef __SOFTFP__
  do_def ("__SOFTFP__");
#endif
#ifdef __SPE__
  do_def ("__SPE__");
#endif
#ifdef __SSE2_MATH__
  do_def ("__SSE2_MATH__");
#endif
#ifdef __SSE2__
  do_def ("__SSE2__");
#endif
#ifdef __SSE3__
  do_def ("__SSE3__");
#endif
#ifdef __SSE_MATH__
  do_def ("__SSE_MATH__");
#endif
#ifdef __SSE__
  do_def ("__SSE__");
#endif
#ifdef __STDCPP__
  do_def ("__STDCPP__");
#endif
#ifdef __STDC_EXT__
  do_def ("__STDC_EXT__");
#endif
#ifdef __STDC_VERSION__
  do_def ("__STDC_VERSION__");
#endif
#ifdef __SVR4
  do_def ("__SVR4");
#endif
#ifdef __SVR4_ABI__
  do_def ("__SVR4_ABI__");
#endif
#ifdef __SYSTYPE_BSD__
  do_def ("__SYSTYPE_BSD__");
#endif
#ifdef __SYSTYPE_SVR4__
  do_def ("__SYSTYPE_SVR4__");
#endif
#ifdef __THUMBEB__
  do_def ("__THUMBEB__");
#endif
#ifdef __THUMBEL__
  do_def ("__THUMBEL__");
#endif
#ifdef __THUMB_INTERWORK__
  do_def ("__THUMB_INTERWORK__");
#endif
#ifdef __UNICOSMK__
  do_def ("__UNICOSMK__");
#endif
#ifdef __UNIX__
  do_def ("__UNIX__");
#endif
#ifdef __USE_INIT_FINI__
  do_def ("__USE_INIT_FINI__");
#endif
#ifdef __UWIN__
  do_def ("__UWIN__");
#endif
#ifdef __UnicomPBD__
  do_def ("__UnicomPBD__");
#endif
#ifdef __VFP_FP__
  do_def ("__VFP_FP__");
#endif
#ifdef __VMS__
  do_def ("__VMS__");
#endif
#ifdef __WIN32__
  do_def ("__WIN32__");
#endif
#ifdef __WINNT__
  do_def ("__WINNT__");
#endif
#ifdef __XTENSA_EB__
  do_def ("__XTENSA_EB__");
#endif
#ifdef __XTENSA_EL__
  do_def ("__XTENSA_EL__");
#endif
#ifdef __XTENSA_SOFT_FLOAT__
  do_def ("__XTENSA_SOFT_FLOAT__");
#endif
#ifdef __XTENSA__
  do_def ("__XTENSA__");
#endif
#ifdef __X_FLOAT
  do_def ("__X_FLOAT");
#endif
#ifdef ____ELF____
  do_def ("____ELF____");
#endif
#ifdef ____LITTLEENDIAN____
  do_def ("____LITTLEENDIAN____");
#endif
#ifdef ____QNXNTO____
  do_def ("____QNXNTO____");
#endif
#ifdef ____QNX____
  do_def ("____QNX____");
#endif
#ifdef ____X86____
  do_def ("____X86____");
#endif
#ifdef __alpha
  do_def ("__alpha");
#endif
#ifdef __alpha__
  do_def ("__alpha__");
#endif
#ifdef __alpha_bwx__
  do_def ("__alpha_bwx__");
#endif
#ifdef __alpha_cix__
  do_def ("__alpha_cix__");
#endif
#ifdef __alpha_ev4__
  do_def ("__alpha_ev4__");
#endif
#ifdef __alpha_ev5__
  do_def ("__alpha_ev5__");
#endif
#ifdef __alpha_ev6__
  do_def ("__alpha_ev6__");
#endif
#ifdef __alpha_fix__
  do_def ("__alpha_fix__");
#endif
#ifdef __alpha_max__
  do_def ("__alpha_max__");
#endif
#ifdef __amd64
  do_def ("__amd64");
#endif
#ifdef __amd64__
  do_def ("__amd64__");
#endif
#ifdef __arc__
  do_def ("__arc__");
#endif
#ifdef __arch64__
  do_def ("__arch64__");
#endif
#ifdef __arm32__
  do_def ("__arm32__");
#endif
#ifdef __arm__
  do_def ("__arm__");
#endif
#ifdef __athlon
  do_def ("__athlon");
#endif
#ifdef __athlon__
  do_def ("__athlon__");
#endif
#ifdef __athlon_sse__
  do_def ("__athlon_sse__");
#endif
#ifdef __base__
  do_def ("__base__");
#endif
#ifdef __big_endian__
  do_def ("__big_endian__");
#endif
#ifdef __bool
  do_def ("__bool");
#endif
#ifdef __bsd4_2__
  do_def ("__bsd4_2__");
#endif
#ifdef __c99
  do_def ("__c99");
#endif
#ifdef __cdecl
  do_def ("__cdecl");
#endif
#ifdef __cris__
  do_def ("__cris__");
#endif
#ifdef __declspec
  do_def ("__declspec");
#endif
#ifdef __digital__
  do_def ("__digital__");
#endif
#ifdef __dsp1600__
  do_def ("__dsp1600__");
#endif
#ifdef __dsp1610__
  do_def ("__dsp1610__");
#endif
#ifdef __embedded__
  do_def ("__embedded__");
#endif
#ifdef __fastcall
  do_def ("__fastcall");
#endif
#ifdef __fr30__
  do_def ("__fr30__");
#endif
#ifdef __frv__
  do_def ("__frv__");
#endif
#ifdef __gcc__
  do_def ("__gcc__");
#endif
#ifdef __gnu_hurd__
  do_def ("__gnu_hurd__");
#endif
#ifdef __gnu_linux__
  do_def ("__gnu_linux__");
#endif
#ifdef __h8300__
  do_def ("__h8300__");
#endif
#ifdef __host_mips__
  do_def ("__host_mips__");
#endif
#ifdef __hp700__
  do_def ("__hp700__");
#endif
#ifdef __hp800__
  do_def ("__hp800__");
#endif
#ifdef __hp9000__
  do_def ("__hp9000__");
#endif
#ifdef __hp9000s200__
  do_def ("__hp9000s200__");
#endif
#ifdef __hp9000s300__
  do_def ("__hp9000s300__");
#endif
#ifdef __hp9000s700
  do_def ("__hp9000s700");
#endif
#ifdef __hp9000s700__
  do_def ("__hp9000s700__");
#endif
#ifdef __hp9000s800
  do_def ("__hp9000s800");
#endif
#ifdef __hp9000s800__
  do_def ("__hp9000s800__");
#endif
#ifdef __hp9k8
  do_def ("__hp9k8");
#endif
#ifdef __hp9k8__
  do_def ("__hp9k8__");
#endif
#ifdef __hppa
  do_def ("__hppa");
#endif
#ifdef __hppa__
  do_def ("__hppa__");
#endif
#ifdef __hpux
  do_def ("__hpux");
#endif
#ifdef __hpux__
  do_def ("__hpux__");
#endif
#ifdef __i370__
  do_def ("__i370__");
#endif
#ifdef __i386__
  do_def ("__i386__");
#endif
#ifdef __i486
  do_def ("__i486");
#endif
#ifdef __i486__
  do_def ("__i486__");
#endif
#ifdef __i586
  do_def ("__i586");
#endif
#ifdef __i586__
  do_def ("__i586__");
#endif
#ifdef __i686
  do_def ("__i686");
#endif
#ifdef __i686__
  do_def ("__i686__");
#endif
#ifdef __i80960__
  do_def ("__i80960__");
#endif
#ifdef __i960__
  do_def ("__i960__");
#endif
#ifdef __ia64
  do_def ("__ia64");
#endif
#ifdef __ia64__
  do_def ("__ia64__");
#endif
#ifdef __iq2000__
  do_def ("__iq2000__");
#endif
#ifdef __itanium__
  do_def ("__itanium__");
#endif
#ifdef __k6
  do_def ("__k6");
#endif
#ifdef __k6_2__
  do_def ("__k6_2__");
#endif
#ifdef __k6_3__
  do_def ("__k6_3__");
#endif
#ifdef __k6__
  do_def ("__k6__");
#endif
#ifdef __k8
  do_def ("__k8");
#endif
#ifdef __k8__
  do_def ("__k8__");
#endif
#ifdef __kaOS__
  do_def ("__kaOS__");
#endif
#ifdef __linux__
  do_def ("__linux__");
#endif
#ifdef __lynx__
  do_def ("__lynx__");
#endif
#ifdef __m32r__
  do_def ("__m32r__");
#endif
#ifdef __m68k__
  do_def ("__m68k__");
#endif
#ifdef __mc68000__
  do_def ("__mc68000__");
#endif
#ifdef __mc68020__
  do_def ("__mc68020__");
#endif
#ifdef __mc68030__
  do_def ("__mc68030__");
#endif
#ifdef __mc68040__
  do_def ("__mc68040__");
#endif
#ifdef __mc68060__
  do_def ("__mc68060__");
#endif
#ifdef __mc68332__
  do_def ("__mc68332__");
#endif
#ifdef __mc68hc1x__
  do_def ("__mc68hc1x__");
#endif
#ifdef __mcf5200__
  do_def ("__mcf5200__");
#endif
#ifdef __mcf528x__
  do_def ("__mcf528x__");
#endif
#ifdef __mcf5300__
  do_def ("__mcf5300__");
#endif
#ifdef __mcf5307__
  do_def ("__mcf5307__");
#endif
#ifdef __mcf5400__
  do_def ("__mcf5400__");
#endif
#ifdef __mcf5407__
  do_def ("__mcf5407__");
#endif
#ifdef __mcfhwdiv__
  do_def ("__mcfhwdiv__");
#endif
#ifdef __mcoldfire__
  do_def ("__mcoldfire__");
#endif
#ifdef __mcore__
  do_def ("__mcore__");
#endif
#ifdef __mcpu32__
  do_def ("__mcpu32__");
#endif
#ifdef __mips16
  do_def ("__mips16");
#endif
#ifdef __mips64
  do_def ("__mips64");
#endif
#ifdef __mips__
  do_def ("__mips__");
#endif
#ifdef __mips_eabi
  do_def ("__mips_eabi");
#endif
#ifdef __mips_hard_float
  do_def ("__mips_hard_float");
#endif
#ifdef __mips_n32
  do_def ("__mips_n32");
#endif
#ifdef __mips_n64
  do_def ("__mips_n64");
#endif
#ifdef __mips_o64
  do_def ("__mips_o64");
#endif
#ifdef __mips_single_float
  do_def ("__mips_single_float");
#endif
#ifdef __mips_soft_float
  do_def ("__mips_soft_float");
#endif
#ifdef __mmix__
  do_def ("__mmix__");
#endif
#ifdef __mn10300__
  do_def ("__mn10300__");
#endif
#ifdef __moss__
  do_def ("__moss__");
#endif
#ifdef __motorola__
  do_def ("__motorola__");
#endif
#ifdef __mvs__
  do_def ("__mvs__");
#endif
#ifdef __netware__
  do_def ("__netware__");
#endif
#ifdef __ns32000__
  do_def ("__ns32000__");
#endif
#ifdef __ns32032__
  do_def ("__ns32032__");
#endif
#ifdef __ns32081__
  do_def ("__ns32081__");
#endif
#ifdef __ns32332__
  do_def ("__ns32332__");
#endif
#ifdef __ns32381__
  do_def ("__ns32381__");
#endif
#ifdef __ns32532__
  do_def ("__ns32532__");
#endif
#ifdef __ns32k__
  do_def ("__ns32k__");
#endif
#ifdef __openedition__
  do_def ("__openedition__");
#endif
#ifdef __osf__
  do_def ("__osf__");
#endif
#ifdef __pa_risc
  do_def ("__pa_risc");
#endif
#ifdef __parisc__
  do_def ("__parisc__");
#endif
#ifdef __pdp11__
  do_def ("__pdp11__");
#endif
#ifdef __pe__
  do_def ("__pe__");
#endif
#ifdef __pentium
  do_def ("__pentium");
#endif
#ifdef __pentium4
  do_def ("__pentium4");
#endif
#ifdef __pentium4__
  do_def ("__pentium4__");
#endif
#ifdef __pentium__
  do_def ("__pentium__");
#endif
#ifdef __pentium_mmx__
  do_def ("__pentium_mmx__");
#endif
#ifdef __pentiumpro
  do_def ("__pentiumpro");
#endif
#ifdef __pentiumpro__
  do_def ("__pentiumpro__");
#endif
#ifdef __pic__
  do_def ("__pic__");
#endif
#ifdef __pixel
  do_def ("__pixel");
#endif
#ifdef __powerpc64__
  do_def ("__powerpc64__");
#endif
#ifdef __powerpc__
  do_def ("__powerpc__");
#endif
#ifdef __ppc__
  do_def ("__ppc__");
#endif
#ifdef __pro__
  do_def ("__pro__");
#endif
#ifdef __riscbsd__
  do_def ("__riscbsd__");
#endif
#ifdef __rs6000__
  do_def ("__rs6000__");
#endif
#ifdef __rtems__
  do_def ("__rtems__");
#endif
#ifdef __s390__
  do_def ("__s390__");
#endif
#ifdef __s390x__
  do_def ("__s390x__");
#endif
#ifdef __semi__
  do_def ("__semi__");
#endif
#ifdef __sgi__
  do_def ("__sgi__");
#endif
#ifdef __sh1__
  do_def ("__sh1__");
#endif
#ifdef __sh2__
  do_def ("__sh2__");
#endif
#ifdef __sh3__
  do_def ("__sh3__");
#endif
#ifdef __sh__
  do_def ("__sh__");
#endif
#ifdef __simulator__
  do_def ("__simulator__");
#endif
#ifdef __sparc
  do_def ("__sparc");
#endif
#ifdef __sparc64__
  do_def ("__sparc64__");
#endif
#ifdef __sparc__
  do_def ("__sparc__");
#endif
#ifdef __sparc_v9__
  do_def ("__sparc_v9__");
#endif
#ifdef __sparclite86x__
  do_def ("__sparclite86x__");
#endif
#ifdef __sparclite__
  do_def ("__sparclite__");
#endif
#ifdef __sparcv9
  do_def ("__sparcv9");
#endif
#ifdef __sparcv9__
  do_def ("__sparcv9__");
#endif
#ifdef __spectrum__
  do_def ("__spectrum__");
#endif
#ifdef __stdcall
  do_def ("__stdcall");
#endif
#ifdef __sun__
  do_def ("__sun__");
#endif
#ifdef __svr4__
  do_def ("__svr4__");
#endif
#ifdef __thumb__
  do_def ("__thumb__");
#endif
#ifdef __tpf__
  do_def ("__tpf__");
#endif
#ifdef __tune_athlon__
  do_def ("__tune_athlon__");
#endif
#ifdef __tune_athlon_sse__
  do_def ("__tune_athlon_sse__");
#endif
#ifdef __tune_i386__
  do_def ("__tune_i386__");
#endif
#ifdef __tune_i486__
  do_def ("__tune_i486__");
#endif
#ifdef __tune_i586__
  do_def ("__tune_i586__");
#endif
#ifdef __tune_i686__
  do_def ("__tune_i686__");
#endif
#ifdef __tune_k6_2__
  do_def ("__tune_k6_2__");
#endif
#ifdef __tune_k6_3__
  do_def ("__tune_k6_3__");
#endif
#ifdef __tune_k6__
  do_def ("__tune_k6__");
#endif
#ifdef __tune_k8__
  do_def ("__tune_k8__");
#endif
#ifdef __tune_pentium2__
  do_def ("__tune_pentium2__");
#endif
#ifdef __tune_pentium3__
  do_def ("__tune_pentium3__");
#endif
#ifdef __tune_pentium4__
  do_def ("__tune_pentium4__");
#endif
#ifdef __tune_pentium__
  do_def ("__tune_pentium__");
#endif
#ifdef __tune_pentium_mmx__
  do_def ("__tune_pentium_mmx__");
#endif
#ifdef __tune_pentiumpro__
  do_def ("__tune_pentiumpro__");
#endif
#ifdef __uClinux__
  do_def ("__uClinux__");
#endif
#ifdef __ultrix__
  do_def ("__ultrix__");
#endif
#ifdef __unix
  do_def ("__unix");
#endif
#ifdef __unix__
  do_def ("__unix__");
#endif
#ifdef __v850
  do_def ("__v850");
#endif
#ifdef __v851__
  do_def ("__v851__");
#endif
#ifdef __vax__
  do_def ("__vax__");
#endif
#ifdef __vector
  do_def ("__vector");
#endif
#ifdef __vms__
  do_def ("__vms__");
#endif
#ifdef __vxworks
  do_def ("__vxworks");
#endif
#ifdef __vxworks__
  do_def ("__vxworks__");
#endif
#ifdef __x86_64
  do_def ("__x86_64");
#endif
#ifdef __x86_64__
  do_def ("__x86_64__");
#endif
#ifdef __xstormy16__
  do_def ("__xstormy16__");
#endif
#ifdef __xtensa__
  do_def ("__xtensa__");
#endif
#ifdef _mips
  do_def ("_mips");
#endif
#ifdef hp9000s800
  do_def ("hp9000s800");
#endif
#ifdef hp9k8
  do_def ("hp9k8");
#endif
#ifdef hppa
  do_def ("hppa");
#endif
#ifdef hpux
  do_def ("hpux");
#endif
#ifdef i860
  do_def ("i860");
#endif
#ifdef mips
  do_def ("mips");
#endif
#ifdef unix
  do_def ("unix");
#endif
