\input texinfo
@setfilename gpc-hr.info
@settitle GNU Pascal priruènik.
@c We use Latin 2 charset for hr_HR language.
@set charset iso-8859-2
@documentencoding iso-8859-2

@c Copyright (C) 1996-2006 Free Software Foundation, Inc.
@c This file is part of the GPC Manual.
@c
@c Authors: J.J. van der Heijden <j.j.vanderheijden@student.utwente.nl>
@c          Peter Gerwinski <peter@gerwinski.de>
@c          Frank Heckenbach <frank@pascal.gnu.de>
@c          Berend de Boer <berend@pobox.com>
@c          Dominik Freche <dominik.freche@mailbox.tu-dresden.de>
@c          Eike Lange <eike@g-n-u.de>
@c
@c Last modification: 2006-02-02 (file up to date)
@c Translator: Mirsad Todorovac <mtodorov_69@yahoo.com>
@set UPDATE-MONTH Jan 2005

@include version.texi

@dircategory GNU programski alati
@direntry
* GPC: (gpc-hr).                GNU Pascal prevodilac (compiler).
@end direntry
@dircategory Pojedini alati
@direntry
* GPC: (gpc-hr)Pozivanje GPC-a. GNU Pascal prevodilac (compiler).
@end direntry

@c For FSF printing, turn on finalout (to get rid of the black
@c boxes) and smallbook; that is all that is needed.
@c @finalout
@iftex
@c @smallbook
@c
@c This is what `\sloppy' does in LaTeX. -- Frank
@emergencystretch 10em@hfuzz 5pt@vfuzz@hfuzz
@end iftex

@syncodeindex fn cp
@syncodeindex vr cp

@c Use with @@smallbook:
@c
@c Cause even numbered pages to be printed on the left hand side of
@c the page and odd numbered pages to be printed on the right hand
@c side of the page. Using this, you can print on both sides of a
@c sheet of paper and have the text on the same part of the sheet.
@c
@c The text on right hand pages is pushed towards the right hand
@c margin and the text on left hand pages is pushed toward the left
@c hand margin.
@c (To provide the reverse effect, set bindingoffset to -0.75in.)
@c
@c @tex
@c \global\bindingoffset=0.75in
@c \global\normaloffset =0.75in
@c @end tex

@c ***************************************************************************

@ifinfo
Ova datoteka dokumentira GPC prevodilac (engl. compiler).

@c Published by the Free Software Foundation
@c 59 Temple Place - Suite 330
@c Boston, MA 02111-1307 USA

Permission is granted to make and distribute verbatim copies of
this manual provided the copyright notice and this permission notice
are preserved on all copies.

Copyright (C) 1988-2006 Free Software Foundation, Inc.

@ignore
Permission is granted to process this file through TeX and print the
results, provided the printed document carries copying permission
notice identical to this one except for the removal of this paragraph
(this paragraph not being relevant to the printed manual).

@end ignore
Permission is granted to copy and distribute modified versions of
this manual under the conditions for verbatim copying, provided also
that the sections entitled ``GNU General Public License'', ``The GNU
Project'', ``The GNU Manifesto'' and ``Funding for free Software''
are included exactly as in the original, and provided that the
entire resulting derived work is distributed under the terms of a
permission notice identical to this one.

Permission is granted to copy and distribute translations of this
manual into another language, under the above conditions for
modified versions, except that the sections entitled ``GNU General
Public License'', ``The GNU Project'', ``The GNU Manifesto'' and
``Funding for Free Software'' and this permission notice, may be
included in translations approved by the Free Software Foundation
instead of in the original English.
@end ifinfo

@setchapternewpage odd

@c ***************************************************************************

@titlepage
@iftex
@vskip-6cm
@image{GnuPascal,,12cm}
@sp 2
@end iftex
@center @titlefont{GNU Pascal priruènik}
@sp 2
@center Jan-Jaap van der Heijden,
@sp 1
@center Peter Gerwinski,
@sp 1
@center Frank Heckenbach,
@sp 1
@center Berend de Boer,
@sp 1
@center Dominik Freche,
@sp 1
@center Eike Lange,
@sp 1
@center and others
@sp 3
@center Zadnja nadopuna @value{UPDATE-MONTH}
@sp 1
@center za version @value{GPCVersion} (GCC @value{GCCVersion})
@page
@vskip 0pt plus 1filll
Copyright @copyright{} 1988-2006 Free Software Foundation, Inc.
@sp 2
For GPC @value{GPCVersion} (GCC @value{GCCVersion})@*
@sp 1
Published by the Free Software Foundation@*
59 Temple Place - Suite 330@*
Boston, MA 02111-1307, USA@*
@c Printed copies are available for $50 each.@*
@sp 1
Permission is granted to make and distribute verbatim copies of
this manual provided the copyright notice and this permission notice
are preserved on all copies.

Permission is granted to copy and distribute modified versions of
this manual under the conditions for verbatim copying, provided also
that the sections entitled ``GNU General Public License'', ``The GNU
Project'', ``The GNU Manifesto'' and ``Funding for Free Software''
are included exactly as in the original, and provided that the
entire resulting derived work is distributed under the terms of a
permission notice identical to this one.

Permission is granted to copy and distribute translations of this
manual into another language, under the above conditions for
modified versions, except that the sections entitled ``GNU General
Public License'', ``The GNU Project'', ``The GNU Manifesto'' and
``Funding for Free Software'' and this permission notice, may be
included in translations approved by the Free Software Foundation
instead of in the original English.
@end titlepage
@summarycontents
@contents
@page

@c ***************************************************************************

@node Top
@top GNU Pascal

Ovaj priruènik dokumentira kako se pokreæe, instalira i odr¾ava GNU Pascal
Compiler (GPC), kao i njegove nove znaèajke i eventualne nekompatibilnosti,
te kako prijavljivati bugove.  Odgovara GPC-u @value{GPCVersion}
(GCC @value{GCCVersion}).

@c It seems that there must be no comments in the menu. -- PG, 2. Aug. 1996
@menu
Uvod:

* Dobrodo¹li::        Dobrodo¹li na GNU Pascal @dots{}
* Naglasci::          Neke od GPC-ovih interesantnih znaèajki.
* News::              Novosti - Nova svojstva GNU Pascala (engleski).
* FAQ::               Lista èesto postavljanih pitanja o GNU Pascalu.

Instalacija:

* Installation::      Instalacija - kako obaviti download, prevesti i
                      instalirati GNU Pascal (engleski).

Kori¹tenje GNU Pascala:

* Invoking GPC::      Pozivanje GPC-a (opcije komandne linije podr¾ane od GNU
                      Pascala).
* Programming::       Programerov vodiè u GPC (engleski).
* Borland Pascal::    Brzi vodiè za prelaz sa Borland Pascala na GNU Pascal.
* Reference::         Abecedni GPC jezièni referentni priruènik (engleski).
* Keywords::          Pascalove kljuène rijeèi i operatori podr¾ani u GPC-u.
* Support::           Gdje dobiti podr¹ku za GNU Pascal; kako prijaviti bug.

Razvoj:

* To Do::             GNU Pascalova "za napraviti" lista (engleski).
* Internals::         Interne strukture - kako dobiti vi¹e informacija o samom
                      GPC-ovom kodu (engleski).

Licence:

* Copying::           Kopiranje -- GNU General Public License -- licenca,
                      va¹a prava i obaveze kad koristite GPC (engl.).
* Library Copying::   Kopiranje biblioteka -- GNU Lesser General Public
                      License -- licenca, va¹a prava i obaveze kod
                      kori¹tenja pojedinih biblioteka (engl.).
* Demo Copying::      GPL uz iznimku -- va¹a prava i obaveze kod kori¹tenja
                      ili modifikacije demo programa.

Dodatak:

* Acknowledgments::   Suradnici na GNU Pascal projektu.
* Resursi::           resursi za kori¹tenje s GPC-om.
* GNU::               GNU projekt.
* Indeks::            Indeks koncepta i imena simbola (nedovr¹eno).

(Napomena: naslovi nekih poglavlja nisu prevedeni zbog unakrsnih referenci iz
           neprevedenih poglavlja priruènika i prema njima. Ponegdje u
           izborniku bi se mogao pojaviti problem oko `è' i sl. zbog buga
           u starijim verzijama - <= 4.0f - GNU `info' programa.)

@end menu

@include welcome.texi
@include about.texi
@include news.texi
@include faq.texi

@include install.texi

@include invoke.texi
@include programming.texi
@include bpqstart.texi
@include reference.texi
@include keywords.texi
@include support.texi

@include todo.texi
@include internals.texi

@include copying.texi
@include copying-lib.texi
@include copying-demo.texi

@include authors.texi
@include resources.texi
@include gnu.texi

@node Indeks
@unnumbered Indeks
@printindex cp

@bye
